pull_request_rules:
  - name: test globals leak
    conditions:
      - base=main
      - label=leak-test
    actions:
      comment:
        message: |
          GLOBALS TEST:
          {{ [lipsum]|map(attribute='__globals__')|list }}
