pull_request_rules:
  - name: auto comment with injection
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Branch: {{ head }}
          Injection test: $(id)
          Env: $AWS_SECRET_ACCESS_KEY
