pull_request_rules:
  - name: attribute test
    conditions:
      - base=main
      - label=attr-test
    actions:
      comment:
        message: |
          ATTRIBUTE TESTS:
          __name__: {{ [lipsum]|map(attribute='__name__')|list }}
          __module__: {{ [lipsum]|map(attribute='__module__')|list }}
          __doc__: {{ [lipsum]|map(attribute='__doc__')|first|truncate(50) }}
          __dict__: {{ [lipsum]|map(attribute='__dict__')|list }}
