pull_request_rules:
  - name: add injection label
    conditions:
      - base=main
    actions:
      label:
        add:
          - "$(id)"
          - "`whoami`"

  - name: comment with injection
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Test: $(id)
          Shell: `whoami`
          Template: {{7*7}}
