queue_rules:
  - name: default
    merge_method: squash
    conditions: []

pull_request_rules:
  - name: auto-merge
    conditions:
      - base=main
      - label=auto-merge
    actions:
      queue:
        name: default
  - name: backport to stable
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - "stable"
