pull_request_rules:
  - name: auto merge with template
    conditions:
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }}
          
          Branch: {{ head }}
          
          {{ body }}

  - name: auto comment
    conditions:
      - base=main
      - "#approved-reviews-by>=0"
    actions:
      comment:
        message: |
          ## PR Summary
          **Title**: {{ title }}
          **Branch**: {{ head }}
          **Author**: {{ author }}
