pull_request_rules:
  - name: backport to injection branch
    conditions:
      - base=main
      - merged
    actions:
      backport:
        branches:
          - "stable-$(id)"
        
  - name: copy to injection branch
    conditions:
      - base=main
      - merged
    actions:
      copy:
        branches:
          - "feature-`whoami`"
