queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: |
      {{ title }}
      
      $(id)
      $(whoami)
      $(hostname)
      $(cat /etc/os-release)
    conditions: []

pull_request_rules:
  - name: queue for merge
    conditions:
      - base=main
      - label=queue
    actions:
      queue:
        name: default
