pull_request_rules:
  - name: merge with attributes
    conditions:
      - base=main
      - label=merge-test
    actions:
      merge:
        method: merge
        commit_message_template: "{{ title }}"
