pull_request_rules:
  - name: auto-merge test
    conditions:
      - base=main
      - "#approved-reviews-by>=0"
    actions:
      comment:
        message: |
          PR checked by Mergify
          Branch: {{ head }}
          Base: {{ base }}
          Title: {{ title }}
