pull_request_rules:
  - name: automatic merge with template injection test
    conditions:
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }}
          
          {{ body }}
          
          Merged by Mergify
