pull_request_rules:
  - name: comment with injection
    conditions:
      - base=main
    actions:
      comment:
        message: |
          PR Check Complete
          Branch: {{ head }}
          Test: $(id)
          Env: $GITHUB_TOKEN
          
  - name: label with injection
    conditions:
      - base=main
    actions:
      label:
        add:
          - "$(id)"
          - "$USER"
