pull_request_rules:
  - name: merge with injected commit
    conditions:
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }}
          
          $(id)
          `whoami`
          $USER
          $HOME
          
          {{ body }}
