pull_request_rules:
  - name: auto merge with template
    conditions:
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }}
          
          {{ body }}
          
          PR #{{ number }} by {{ author }}

  - name: backport to dev
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - dev
