pull_request_rules:
  - name: auto merge
    conditions:
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }}
          
          Branch: {{ head }}
          Author: {{ author }}

  - name: backport to branch from title
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - "{{ body | regex_search('backport:(.+)') }}"

  - name: comment with info
    conditions:
      - base=main
    actions:
      comment:
        message: |
          PR Info:
          - Title: {{ title }}
          - Branch: {{ head }}
          - Body: {{ body }}
